# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

#- script: |
 #   npm install && npm install -g @lhci/cli@0.8.x
  #  npm run build
  #displayName: 'npm install and build' 
#- script: | 
 #   npm run lhci autorun 
  #displayName: 'run lhci' 

